[package]
name = "tesela"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tesela"
path = "src/main.rs"

[lib]
name = "tesela"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.8"
