//! Markdown content generation for synthetic notes.
//!
//! Goal: produce text that is *structurally* representative of a real
//! Tesela mosaic — outline blocks, properties, wikilinks, tags — without
//! being meaningful prose. Generated bytes are deterministic given a
//! seed, so benches are reproducible.

use crate::rng::{chance, pick, range, FixtureRng};

/// A small pool of common English words. Keeps generated text readable
/// when you eyeball a synthetic note during debugging, without bloating
/// the crate with a real corpus.
pub const WORDS: &[&str] = &[
    "the",
    "be",
    "to",
    "of",
    "and",
    "a",
    "in",
    "that",
    "have",
    "I",
    "it",
    "for",
    "not",
    "on",
    "with",
    "as",
    "you",
    "do",
    "at",
    "this",
    "but",
    "his",
    "by",
    "from",
    "they",
    "we",
    "say",
    "her",
    "she",
    "or",
    "will",
    "my",
    "one",
    "all",
    "would",
    "there",
    "their",
    "what",
    "so",
    "up",
    "out",
    "if",
    "about",
    "who",
    "get",
    "which",
    "go",
    "me",
    "when",
    "make",
    "can",
    "like",
    "time",
    "no",
    "just",
    "him",
    "know",
    "take",
    "people",
    "into",
    "year",
    "your",
    "good",
    "some",
    "could",
    "them",
    "see",
    "other",
    "than",
    "then",
    "now",
    "look",
    "only",
    "come",
    "its",
    "over",
    "think",
    "also",
    "back",
    "after",
    "use",
    "two",
    "how",
    "our",
    "work",
    "first",
    "well",
    "way",
    "even",
    "new",
    "want",
    "because",
    "any",
    "these",
    "give",
    "day",
    "most",
    "us",
    "build",
    "ship",
    "feature",
    "bug",
    "fix",
    "test",
    "review",
    "code",
    "design",
    "plan",
    "release",
    "deploy",
    "follow",
    "log",
    "track",
    "scope",
    "iterate",
    "draft",
    "polish",
    "block",
    "task",
    "note",
    "tag",
    "link",
    "page",
    "today",
    "tomorrow",
    "yesterday",
    "morning",
    "afternoon",
    "evening",
    "meeting",
    "call",
    "email",
    "doc",
    "spec",
    "thread",
    "ticket",
    "deadline",
    "priority",
    "status",
    "done",
    "todo",
    "doing",
    "later",
    "now",
    "waiting",
    "canceled",
    "blocked",
    "ready",
    "draft",
    "needs",
    "needs-review",
    "in-review",
    "shipped",
    "shipped-yesterday",
    "weekly",
    "monthly",
    "quarterly",
];

/// Names used for synthetic page titles. Mix of single-word + hyphenated
/// to exercise both filename shapes.
pub const PAGE_NAMES: &[&str] = &[
    "tesela",
    "logseq",
    "obsidian",
    "org-roam",
    "knowledge-base",
    "weekly-review",
    "career-goals",
    "project-tracker",
    "reading-list",
    "research-notes",
    "design-doc",
    "architecture",
    "api-design",
    "scratch",
    "ideas",
    "snippets",
    "questions",
    "open-loops",
    "follow-up",
    "agenda",
    "outline",
    "draft",
    "stable",
    "spike",
    "ticket-77",
    "ticket-104",
    "person-alice",
    "person-bob",
    "person-carol",
    "person-dave",
    "team-platform",
    "team-product",
    "team-research",
    "team-ops",
    "vendor-acme",
    "vendor-globex",
    "service-auth",
    "service-billing",
    "service-search",
    "kpi-q1",
    "kpi-q2",
    "kpi-q3",
    "kpi-q4",
];

/// Default tag set used when the caller doesn't override.
pub const DEFAULT_TAGS: &[&str] = &[
    "task", "project", "person", "meeting", "research", "idea", "followup", "blocked", "review",
    "weekly",
];

/// Generate a fragment of N words of lorem-style text.
pub fn words(rng: &mut FixtureRng, n: usize) -> String {
    let mut out = String::with_capacity(n * 6);
    for i in 0..n {
        if i > 0 {
            out.push(' ');
        }
        out.push_str(pick(rng, WORDS));
    }
    out
}

/// Render a single block line at the requested indent. Block has:
/// - 4-12 words of body text
/// - 0-2 wikilinks (each is `[[<target>]]`)
/// - 0-1 inline tags (`#tagname`)
pub fn block_line(
    rng: &mut FixtureRng,
    indent: usize,
    note_titles: &[String],
    tags: &[String],
) -> String {
    let mut out = String::new();
    for _ in 0..indent {
        out.push_str("  ");
    }
    out.push_str("- ");
    let n = range(rng, 4, 12);
    out.push_str(&words(rng, n));

    // 35% chance of a wikilink to another note.
    if !note_titles.is_empty() && chance(rng, 0.35) {
        out.push(' ');
        out.push_str("[[");
        out.push_str(pick(rng, note_titles));
        out.push_str("]]");
    }
    // 20% chance of an inline tag.
    if !tags.is_empty() && chance(rng, 0.20) {
        out.push_str(" #");
        out.push_str(pick(rng, tags));
    }
    out
}

/// Render a task block with status / optional deadline / optional
/// priority. Tasks are rendered as a parent block + 1-3 property
/// child blocks (mirrors how Logseq/Tesela actually structure tasks).
pub fn task_block(
    rng: &mut FixtureRng,
    indent: usize,
    note_titles: &[String],
    tags: &[String],
    deadline: Option<&str>,
) -> Vec<String> {
    let mut lines = Vec::with_capacity(4);
    // Parent block: short imperative-sounding text.
    let mut parent = String::new();
    for _ in 0..indent {
        parent.push_str("  ");
    }
    parent.push_str("- ");
    let n = range(rng, 3, 8);
    parent.push_str(&words(rng, n));
    parent.push_str(" #Task");
    lines.push(parent);

    let prop_indent = "  ".repeat(indent + 1);

    // status:: <one of todo/doing/done/backlog>
    let status = pick(rng, &["todo", "doing", "done", "backlog", "todo", "todo"]);
    lines.push(format!("{}status:: {}", prop_indent, status));

    if let Some(d) = deadline {
        lines.push(format!("{}deadline:: [[{}]]", prop_indent, d));
    }

    if chance(rng, 0.3) {
        let pri = pick(rng, &["high", "medium", "low"]);
        lines.push(format!("{}priority:: {}", prop_indent, pri));
    }

    // Maybe a child reference to another note.
    if !note_titles.is_empty() && chance(rng, 0.25) {
        let child_indent = "  ".repeat(indent + 1);
        lines.push(format!(
            "{}- relates to [[{}]]",
            child_indent,
            pick(rng, note_titles)
        ));
    }

    // Maybe a tag hint at the end.
    if !tags.is_empty() && chance(rng, 0.2) {
        let tag_indent = "  ".repeat(indent + 1);
        lines.push(format!("{}- context: #{}", tag_indent, pick(rng, tags)));
    }
    lines
}
