// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which dated property the row's anchor came from. Surfaced so clients
 * can distinguish ⚑ deadline (a date the work *must* be done by — a
 * commitment to others / a hard cutoff) from 🕒 scheduled (a date the
 * user picked for *doing* the work — a self-commitment). Drives the
 * Todoist-style split of the Overdue bucket into two sub-buckets
 * because rescheduling a missed deadline is semantically different
 * from rescheduling a missed planned-do date.
 *
 * When a block carries both `deadline::` and `scheduled::`, the agenda
 * query anchors on `scheduled` (the "when am I doing it" answer), so
 * `field` is `Scheduled` in that case.
 */
export type AgendaField = "deadline" | "scheduled";
