// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgendaField } from "./AgendaField";
import type { AgendaRowKind } from "./AgendaRowKind";

/**
 * One row in an agenda view — either a task or an event within a date window.
 */
export type AgendaRow = { block_id: string, source_note_id: string, 
/**
 * YYYY-MM-DD of the occurrence (anchor for non-recurring; a projected
 * future date for recurring projections).
 */
occurrence_date: string, 
/**
 * Optional HH:MM if the source date carries a time.
 */
occurrence_time: string | null, kind: AgendaRowKind, 
/**
 * `true` if `occurrence_date` is before today at query time.
 */
overdue: boolean, 
/**
 * The block's `recurring::` value (canonical string) when projecting; `None` otherwise.
 */
recurrence: string | null, 
/**
 * `true` for the block's current anchor; `false` for projected future occurrences.
 */
is_anchor: boolean, 
/**
 * The block's text (sans `status::`/`deadline::`/etc. property lines).
 */
text: string, 
/**
 * `status::` value (`"todo"`, `"done"`, ...) for task rows; `None` for events.
 */
status: string | null, 
/**
 * Which dated property the row's anchor came from. See [`AgendaField`].
 */
field: AgendaField, };
