// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an agenda row represents a task or a calendar event.
 */
export type AgendaRowKind = "task" | "event";
