// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";

/**
 * Represents an attachment
 */
export type Attachment = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Original filename
 */
filename: string, 
/**
 * MIME type
 */
mime_type: string, 
/**
 * File size in bytes
 */
size: bigint, 
/**
 * SHA256 checksum
 */
checksum: string, 
/**
 * Path relative to attachments directory
 */
path: string, 
/**
 * Associated note IDs
 */
note_ids: Array<NoteId>, };
