// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Predicate } from "./Predicate";

/**
 * Boolean expression tree built by `parse_query`. The DSL is now a real
 * algebra over predicates — `AND` / `OR` / `NOT` / parens — so a single
 * flat predicate list (the legacy `filters` field) can't represent
 * every parseable query. The matcher walks this tree; the legacy
 * `filters` field is populated only when the tree is a flat AND of
 * simple `Cmp` atoms, for SQL-prefilter compatibility.
 */
export type BoolExpr = { "op": "and", args: Array<BoolExpr>, } | { "op": "or", args: Array<BoolExpr>, } | { "op": "not", arg: BoolExpr, } | { "op": "atom", pred: Predicate, };
