// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayMarkers } from "./DayMarkers";

/**
 * Calendar marks payload — keys are `YYYY-MM-DD` strings.
 */
export type CalendarMarks = { days: { [key in string]: DayMarkers }, };
