// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-day marker counts surfaced in the rail's mini calendar (Phase 9.2).
 */
export type DayMarkers = { 
/**
 * Blocks with `deadline:: <date>` due that day.
 */
tasks: number, 
/**
 * Blocks with `scheduled:: <date>` on that day.
 */
events: number, 
/**
 * Whether a daily note exists for this date.
 */
notes: boolean, };
