// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight source→target pair for graph rendering
 */
export type GraphEdge = { source: string, target: string, };
