// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkType } from "./LinkType";

/**
 * Extracted link from markdown
 */
export type Link = { 
/**
 * Type of link (internal, external, attachment)
 */
link_type: LinkType, 
/**
 * Target of the link
 */
target: string, 
/**
 * Link text
 */
text: string, 
/**
 * Position in the document (byte offset)
 */
position: number, };
