// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Note metadata extracted from frontmatter
 */
export type NoteMetadata = { 
/**
 * Note title from frontmatter (overrides extracted title)
 */
title: string | null, 
/**
 * Tags associated with the note
 */
tags: Array<string>, 
/**
 * Note aliases for easier searching
 */
aliases: Array<string>, 
/**
 * Page type (e.g., "Task", "Project", "Person")
 */
note_type: string | null, 
/**
 * Custom key-value pairs
 */
custom: Record<string, unknown>, 
/**
 * Creation date from frontmatter
 */
created: string | null, 
/**
 * Last modified date from frontmatter
 */
modified: string | null, };
