// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";

/**
 * A historical version of a note. Created on every successful PUT (Phase 9.3).
 */
export type NoteVersion = { 
/**
 * Auto-incrementing primary key.
 */
id: bigint, note_id: NoteId, 
/**
 * Per-note monotonically increasing version number (1-based).
 */
version_number: bigint, 
/**
 * Snapshot of `notes.content` after this PUT.
 */
content: string, 
/**
 * What `notes.content` looked like before this PUT (for `+N/-M` diff).
 */
prev_content: string | null, 
/**
 * ISO timestamp of when the row was written.
 */
created_at: string, };
