// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { NoteId } from "./NoteId";
import type { NoteMetadata } from "./NoteMetadata";

/**
 * Represents a note with its metadata and content
 */
export type Note = { 
/**
 * Unique identifier for the note (usually filename without extension)
 */
id: NoteId, 
/**
 * Note title
 */
title: string, 
/**
 * Full content including frontmatter
 */
content: string, 
/**
 * Parsed body content (without frontmatter)
 */
body: string, 
/**
 * Frontmatter metadata
 */
metadata: NoteMetadata, 
/**
 * File path relative to mosaic root
 */
path: string, 
/**
 * SHA256 checksum of the content
 */
checksum: string, 
/**
 * Creation timestamp
 */
created_at: string, 
/**
 * Last modification timestamp
 */
modified_at: string, 
/**
 * List of attachments
 */
attachments: Array<Attachment>, };
