// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Immutable identity used by typed page relations.
 *
 * It is deliberately separate from slug-keyed [`NoteId`] and from the
 * legacy Loro stream address. New identities are deterministically backfilled
 * from the current address, then persisted in note authority and never
 * recomputed.
 */
export type PageId = string;
