// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoolExpr } from "./BoolExpr";
import type { Kind } from "./Kind";
import type { QueryFilter } from "./QueryFilter";

/**
 * A parsed query: a `Kind`, the canonical expression tree (`expr`), and
 * a legacy flat-AND view (`filters`) populated only for queries that
 * happen to be expressible as one. Code that needs to filter blocks
 * reads `expr`; code that wants to do SQL-level pre-filtering can
 * inspect `filters` and degrade to "no prefilter" when it's empty.
 */
export type ParsedQuery = { kind: Kind, 
/**
 * Canonical boolean expression. Always set; defaults to an empty
 * `And` (matches everything) for the empty query string.
 */
expr: BoolExpr, 
/**
 * Legacy flat-AND view. Populated only when `expr` is a flat
 * conjunction of `Cmp` atoms (no `OR` / `NOT IN` / parens). Empty
 * otherwise — readers must handle that gracefully (the SQL
 * prefilter in `db/sqlite.rs::execute_block_query` does).
 */
filters: Array<QueryFilter>, 
/**
 * `ORDER BY` clause from the DSL — pre-composed into the comma-
 * separated `"key1 desc, key2 asc, key3"` shape that
 * `db::sqlite::apply_sort` already accepts. `None` when the query
 * has no `ORDER BY`, in which case the caller's external `sort`
 * param (e.g. the HTTP body's `sort` field) is the fallback.
 */
sort?: string, 
/**
 * Syntax diagnostics. Additive so existing callers can continue using
 * the boolean matcher while authoring surfaces explain fail-closed input.
 */
diagnostics: Array<string>, };
