// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";
import type { QueryFilter } from "./QueryFilter";

/**
 * A parsed query: a `Kind` plus a flat list of filters that all must match.
 */
export type ParsedQuery = { kind: Kind, filters: Array<QueryFilter>, };
