// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed block from a note body.
 */
export type ParsedBlock = { 
/**
 * Deterministic ID: `{note_id}:{line_number}`
 */
id: string, 
/**
 * Canonical block UUID parsed from the on-disk `<!-- bid:UUID -->`
 * marker. `None` for blocks the server hasn't yet stamped (brand-
 * new local blocks before their first round-trip through
 * `stamp_block_ids`). Surfaced so clients can re-emit the bid on
 * save instead of dropping it — dropping it caused the server
 * to re-stamp a fresh UUID on every save, which then appended a
 * duplicate file row via `apply_block_upsert`.
 */
bid?: string | null, 
/**
 * The block's display text (first line without tags)
 */
text: string, 
/**
 * Full raw text including continuation lines
 */
raw_text: string, 
/**
 * Tags found directly on this block (e.g., ["Task", "urgent"]).
 * Union of `inline_tags`, `trailing_tags`, and any `tags::` property
 * value. Kept as a single flat list for back-compat with surfaces that
 * don't care about position.
 */
tags: Array<string>, 
/**
 * `#tag` tokens that appear inside the block's text content (not at the
 * trailing cluster). These render inline in the editor.
 */
inline_tags: Array<string>, 
/**
 * `#tag` tokens that appear in the trailing-cluster (one or more
 * `#tag` tokens at the very end of the block's raw text, separated
 * only by whitespace). These render as chips at the end of the block.
 * Drives the tag-system spec's chip-vs-inline rendering.
 */
trailing_tags: Array<string>, 
/**
 * Tags inherited from ancestor blocks (parent, grandparent, etc.)
 */
inherited_tags: Array<string>, 
/**
 * Properties extracted from the block (e.g., {"status": "todo"})
 */
properties: { [key in string]: string }, 
/**
 * Indentation level (0 = root)
 */
indent_level: number, 
/**
 * The note this block belongs to
 */
note_id: string, 
/**
 * `note_type` of the containing page when known. Populated by the
 * query candidate path (`SqliteIndex::execute_block_query`) so the
 * `on:system-pages` DSL clause can filter blocks by their parent
 * note's type without re-fetching note metadata at filter time.
 * `None` for the standalone `parse_blocks(note_id, body)` form —
 * `on:*` predicates that rely on parent metadata gracefully
 * degrade (they match no block) rather than error.
 */
parent_note_type: string | null, };
