// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed block from a note body.
 */
export type ParsedBlock = { 
/**
 * Deterministic ID: `{note_id}:{line_number}`
 */
id: string, 
/**
 * The block's display text (first line without tags)
 */
text: string, 
/**
 * Full raw text including continuation lines
 */
raw_text: string, 
/**
 * Tags found in the block (e.g., ["Task", "urgent"])
 */
tags: Array<string>, 
/**
 * Properties extracted from the block (e.g., {"status": "todo"})
 */
properties: { [key in string]: string }, 
/**
 * Indentation level (0 = root)
 */
indent_level: number, 
/**
 * The note this block belongs to
 */
note_id: string, };
