// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryOp } from "./QueryOp";

/**
 * A single leaf predicate in the boolean expression tree. Carries either
 * a comparison (`key OP value`) or set membership (`key IN (…)` /
 * `key NOT IN (…)`). All other DSL constructs (negation, conjunction,
 * disjunction, grouping) live at the [`BoolExpr`] level.
 */
export type Predicate = { "kind": "cmp", key: string, op: QueryOp, value: string, } | { "kind": "in", key: string, values: Array<string>, 
/**
 * `true` for `NOT IN`; flips the membership check.
 */
negated: boolean, };
