// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A property definition within a type
 */
export type PropertyDef = { name: string, value_type: string, values: Array<string> | null, default: string | null, required: boolean, };
