// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Visibility } from "./Visibility";

/**
 * A property definition within a type
 */
export type PropertyDef = { name: string, value_type: string, values: Array<string> | null, default: string | null, required: boolean, 
/**
 * Per-type visibility, resolved from the type's `property_overrides`
 * (`show`) or derived from `hide_by_default` when no override exists.
 * `None` only when this PropertyDef was produced outside the per-type
 * resolver (e.g. `get_all_property_defs`).
 */
show: Visibility | null, 
/**
 * If true, the property is hidden from the block by default. The user
 * must expand the block's "show properties" affordance (chevron) to see
 * it. Inspired by Logseq DB's per-tag-property "Hide by default" toggle.
 */
hide_by_default: boolean, 
/**
 * If true, the property only renders when its value is non-empty. Empty
 * property lines are suppressed. Defaults to true (most users want this).
 */
hide_empty: boolean, };
