// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Comparison operator on a filter value.
 */
export type QueryOp = "Eq" | "Ne" | "Gt" | "Lt" | "Gte" | "Lte" | "Like" | "NotLike";
