// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";

/**
 * One row in a [`QueryResult`] — either a block or a whole page.
 */
export type QueryItem = { 
/**
 * Present when the row is a block; `None` for page-kind rows.
 */
block_id: string | null, 
/**
 * The containing page (or, for page-kind rows, the page itself).
 */
page_id: string, 
/**
 * Page title.
 */
title: string, 
/**
 * Display text — block's first line, or the page title for page-kind rows.
 */
text: string, 
/**
 * Ancestor chain in the block's containing page (page title, then root
 * block text, …). Empty for page-kind rows.
 */
parent_breadcrumb: Array<string>, 
/**
 * Mirrors the query's [`Kind`].
 */
kind: Kind, 
/**
 * First tag in the block's resolved chain (used for kind glyphs).
 */
primary_tag: string | null, 
/**
 * Block-level properties (or page metadata for page rows).
 */
properties: { [key in string]: string }, };
