// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryGroup } from "./QueryGroup";

export type QueryResult = { groups: Array<QueryGroup>, };
