// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryOp } from "./QueryOp";

/**
 * One filter token in the parsed query. Legacy flat-AND view; populated
 * only when the parsed expression is a flat conjunction of simple
 * `key OP value` predicates. Queries with `OR` / parens / `IN (…)` /
 * `NOT IN (…)` produce an empty `filters` and live entirely in `expr`.
 */
export type QueryFilter = { 
/**
 * Lowercased filter key (e.g. `tag`, `status`, `has`, or a custom property).
 */
key: string, 
/**
 * Comparison op. Negation flips `Eq` to `Ne` etc., applied during parse.
 */
op: QueryOp, 
/**
 * The filter value. Empty string for `has:` predicates.
 */
value: string, };
