// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageId } from "./PageId";

/**
 * One resolver candidate supplied to relation-aware query matching.
 */
export type QueryPage = { page_id: PageId, slug: string, title: string, aliases: Array<string>, deleted: boolean, };
