// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryOp } from "./QueryOp";

/**
 * One filter token in the parsed query.
 */
export type QueryFilter = { 
/**
 * Lowercased filter key (e.g. `tag`, `status`, `has`, or a custom property).
 */
key: string, 
/**
 * Comparison op. Negation flips `Eq` to `Ne` etc., applied during parse.
 */
op: QueryOp, 
/**
 * The filter value. Empty string for `has:` predicates.
 */
value: string, };
