// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryItem } from "./QueryItem";

/**
 * Grouped query result.
 */
export type QueryGroup = { 
/**
 * Group label (e.g. `"DOING"`, `"TODAY"`, or empty for "ungrouped").
 */
key: string, 
/**
 * Number of items in this group.
 */
count: number, items: Array<QueryItem>, };
