// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelationEdge } from "./RelationEdge";

/**
 * Relation backlink plus source display context.
 */
export type RelationBacklink = { edge: RelationEdge, source_slug: string, source_title: string, };
