// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageId } from "./PageId";

/**
 * Rebuildable typed relation projection. It is intentionally separate from
 * [`Link`] so wiki-link storage and consumers remain unchanged.
 */
export type RelationEdge = { source_page_id: PageId, source_note_id: string, source_block_id: string | null, property_key: string, target_page_id: PageId, };
