// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyDef } from "./PropertyDef";

/**
 * A type definition (e.g., Task, Project, Person)
 */
export type TypeDefinition = { name: string, description: string, icon: string, color: string, properties: Array<PropertyDef>, };
