// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The canonical value-type vocabulary — THE one source of truth for what a
 * property's `value_type` string may mean, across Rust, web (`PropertyType`
 * in `property-registry.ts`), and iOS (`PropertyType` in
 * `PropertyRegistry.swift`). `crate::types::PropertyDef::value_type` stores
 * this vocabulary's string form (`as_str()`), parsed back via [`parse`] —
 * there is no second, independently-validated type vocabulary in Rust.
 * Unknown strings degrade to `Text` (coerce-and-keep: validation is a view,
 * never a gate).
 */
export type ValueType = "text" | "number" | "date" | "datetime" | "checkbox" | "url" | "select" | "multiselect" | "node" | "email" | "phone" | "object";
