// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-type visibility for a property (Anytype/Logseq-DB 3-state model).
 *
 * - `OnNew` — auto-seeded onto a new block of the type (and its default
 *   applied); always shown. Legacy equivalent: `hide_by_default = false`.
 * - `OnSet` — settable but not auto-seeded; shown only when it has a
 *   value (per-type `hide_empty` semantics).
 * - `Hidden` — never seeded; available in `/p` but hidden when empty.
 *   Legacy equivalent: `hide_by_default = true`.
 *
 * Serializes as the same `on_new` / `on_set` / `hidden` strings used in
 * `property_overrides.{Prop}.show` FLOW YAML.
 */
export type Visibility = "on_new" | "on_set" | "hidden";
