//! Rust-generated recurrence-DSL conformance fixture
//! (`tests/fixtures/recurrence-conformance.json`).
//!
//! Unlike `query-conformance.json` (hand-authored), this fixture is
//! GENERATED by this test from the case table below: `valid` comes
//! straight from the real Rust parser (`tesela_core::recurrence::parse`),
//! so the fixture can never drift from what Rust actually accepts.
//!
//! `canonical_display` is hand-canonicalized on the WEB TS output
//! (`web/src/lib/recurrence-format.ts`'s `formatRecurrence`) — the web
//! client keeps its own TS mirror until the wasm pipeline (tesela-pfix.5)
//! lands. As of tesela-pfix.2, `tesela_core::recurrence::format` is ALSO
//! a real Rust formatter (iOS now calls it through the FFI instead of
//! carrying its own Swift mirror); `format_matches_rust_formatter` below
//! asserts every case's `canonical_display` round-trips through it, so
//! Rust/web/iOS can't silently drift apart. The web and iOS conformance
//! runners (`web/tests/unit/recurrence-conformance.test.mjs`,
//! `app/Tesela-iOS/Tests/RecurrenceConformanceTests.swift`) assert their
//! REAL `formatRecurrence` (web) / the FFI-backed `RecurrenceFormat.human`
//! (iOS) output against this field too, so drift between the clients is
//! caught immediately.
//!
//! Both `valid` and `canonical_display` are independent, structurally
//! computed properties — `canonical_display` is NOT reset to the raw
//! input just because `valid` is false; it reflects whatever the display
//! formatter's own (looser) matching produces. See the `every 0 days`-style
//! cases in `recurrence.rs`'s own unit tests for why the two can diverge;
//! this fixture deliberately avoids those known landmines and sticks to
//! clean, unambiguous accept/reject cases so canonical_display is
//! predictable across languages.
//!
//! Case shape: { name, input, valid, canonical_display }
//!   name              — unique snake_case id, used as the assertion message.
//!   input             — the RAW string as it would appear in `recurring::`.
//!   valid             — `tesela_core::recurrence::parse(input).is_some()`.
//!   canonical_display — `formatRecurrence(input)` (web); mirrors
//!                       `RecurrenceFormat.human(input)` (iOS). For
//!                       genuinely unrecognized input this equals the raw
//!                       `input` (the formatter's documented "return
//!                       unchanged" fallback).
//!
//! `client_extraction_cases` is a CLIENT-ONLY section (see
//! `_client_extraction_contract` in the fixture) covering the trailing
//! date+recurrence EXTRACTION path (`parseDateAndRecurrenceInput` / Swift's
//! `DateParser.parse`) — lifting a recurrence tail off mixed
//! "<date phrase> <recurrence phrase>" input. `tesela_core::recurrence`
//! only parses bare recurrence strings; it has no mixed-text extraction
//! concept, so unlike `cases` above this section is NOT derived from a
//! Rust function — the expected values are pinned literals (verified
//! against the real web `parseDateAndRecurrenceInput` before being
//! committed here). Rust still owns writing/comparing this section so the
//! on-disk fixture has exactly one generator.

use serde::Serialize;
use tesela_core::recurrence::{format, parse};

#[derive(Serialize)]
struct Case {
    name: String,
    input: String,
    valid: bool,
    canonical_display: String,
}

#[derive(Serialize)]
struct ExpectedExtraction {
    date: String,
    time: Option<String>,
    recurrence: Option<String>,
    field: Option<String>,
}

#[derive(Serialize)]
struct ClientExtractionCase {
    name: String,
    input: String,
    /// `YYYY-MM-DD` — the fixed "today" anchor both clients pass to
    /// `parseDateAndRecurrenceInput` / `DateParser.parse` for this case.
    anchor_date: String,
    /// `None` means the extraction call is expected to return null
    /// (no date recognized, no bare-recurrence fallback either).
    expected: Option<ExpectedExtraction>,
}

#[derive(Serialize)]
struct Fixture {
    _contract: Vec<String>,
    cases: Vec<Case>,
    _client_extraction_contract: Vec<String>,
    client_extraction_cases: Vec<ClientExtractionCase>,
}

fn fixture_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/recurrence-conformance.json")
}

/// (name, input, display-when-valid). `valid` is derived from the REAL
/// parser, not asserted here — that's the whole point of generating this
/// fixture from Rust. For inputs the parser rejects, the display column is
/// still meaningful (see module docs) and is filled in per-case below.
fn raw_cases() -> Vec<(&'static str, &'static str, &'static str)> {
    vec![
        // Baseline keywords — unaffected by the 2026-06-20 grammar addition;
        // regression pins so the new cases below can't silently break these.
        ("daily", "daily", "Daily"),
        ("weekly", "weekly", "Weekly"),
        ("monthly", "monthly", "Monthly"),
        ("yearly", "yearly", "Yearly"),
        ("weekdays", "weekdays", "Weekdays"),
        ("weekends", "weekends", "Weekends"),
        ("every_n_weeks", "every 2 weeks", "Every 2 weeks"),
        ("every_n_days", "every 3 days", "Every 3 days"),
        ("every_1_day", "every 1 day", "Every 1 day"),
        ("every_6_months", "every 6 months", "Every 6 months"),
        ("every_2_years", "every 2 years", "Every 2 years"),
        ("byday_single_mon", "every mon", "Mon"),
        ("byday_multi_mwf", "every mon, wed, fri", "Mon, Wed, Fri"),
        // Display preserves the RAW token order (only the parser normalizes
        // to Mon..Sun order) — deliberately unsorted input.
        ("byday_multi_unsorted_input", "every fri, mon", "Fri, Mon"),
        (
            "until_clause",
            "weekly until 2026-12-31",
            "Weekly until Dec 31, 2026",
        ),
        ("count_clause", "daily count 3", "Daily, 3×"),
        (
            "byday_until",
            "every mon, fri until 2026-12-31",
            "Mon, Fri until Dec 31, 2026",
        ),
        // New grammar (2026-06-20): biweekly/fortnightly/quarterly/every-other/every-weekday.
        ("biweekly", "biweekly", "Biweekly"),
        ("fortnightly", "fortnightly", "Fortnightly"),
        ("quarterly", "quarterly", "Quarterly"),
        ("quarterly_case_insensitive", "Quarterly", "Quarterly"),
        ("biweekly_mixed_whitespace", "  Biweekly  ", "Biweekly"),
        ("biweekly_count", "biweekly count 4", "Biweekly, 4×"),
        (
            "quarterly_until",
            "quarterly until 2027-06-01",
            "Quarterly until Jun 1, 2027",
        ),
        ("every_other_day", "every other day", "Every other day"),
        (
            "every_other_days_plural",
            "every other days",
            "Every other day",
        ),
        ("every_other_week", "every other week", "Every other week"),
        (
            "every_other_weeks_plural",
            "every other weeks",
            "Every other week",
        ),
        (
            "every_other_month",
            "every other month",
            "Every other month",
        ),
        ("every_other_year", "every other year", "Every other year"),
        (
            "every_other_year_until",
            "every other year until 2030-01-01",
            "Every other year until Jan 1, 2030",
        ),
        (
            "every_other_month_count",
            "every other month count 6",
            "Every other month, 6×",
        ),
        ("every_weekday", "every weekday", "Weekdays"),
        ("every_weekdays_alias", "every weekdays", "Weekdays"),
        (
            "every_weekday_until",
            "every weekday until 2026-08-01",
            "Weekdays until Aug 1, 2026",
        ),
        // Clean rejects — both the parser and the display formatter fail to
        // structurally match, so canonical_display is the raw input.
        ("empty", "", ""),
        ("garbage", "blarg", "blarg"),
        ("every_alone", "every", "every"),
        (
            "every_2_fortnights",
            "every 2 fortnights",
            "every 2 fortnights",
        ),
        (
            "every_other_fortnight",
            "every other fortnight",
            "every other fortnight",
        ),
        (
            "every_other_unknown_unit",
            "every other decade",
            "every other decade",
        ),
        (
            "byday_unknown_token",
            "every mon, blarg",
            "every mon, blarg",
        ),
        ("biweekly_extra_word", "biweekly extra", "biweekly extra"),
    ]
}

/// Expected extraction result: `(date, time, recurrence, field)`, or `None`
/// when the whole `parseDateAndRecurrenceInput` / `DateParser.parse` call
/// is expected to return null.
type ExtractionExpected =
    Option<(&'static str, Option<&'static str>, Option<&'static str>, Option<&'static str>)>;

/// (name, input, anchor_date, expected). All anchored to the same
/// `2026-05-22` (Fri May 22 2026) reference date the existing
/// `date-parser.test.mjs` suite already uses, so both clients construct
/// the identical "today" for relative words like "tomorrow"/"next friday".
/// Exercises the trailing-recurrence EXTRACTION path (not standalone
/// `parseRecurrenceInput`) for the new grammar: biweekly/fortnightly/
/// quarterly/"every other <unit>"/"every weekday(s)".
fn client_extraction_raw_cases() -> Vec<(&'static str, &'static str, &'static str, ExtractionExpected)>
{
    vec![
        (
            "extract_biweekly_tomorrow",
            "tomorrow biweekly",
            "2026-05-22",
            Some(("2026-05-23", None, Some("biweekly"), None)),
        ),
        (
            "extract_fortnightly_month_day",
            "aug 1 fortnightly",
            "2026-05-22",
            Some(("2026-08-01", None, Some("fortnightly"), None)),
        ),
        (
            "extract_quarterly_until_clause",
            "sep 15 quarterly until 2027-01-01",
            "2026-05-22",
            Some(("2026-09-15", None, Some("quarterly until 2027-01-01"), None)),
        ),
        (
            "extract_every_other_week_with_weekday_date",
            "friday every other week",
            "2026-05-22",
            Some(("2026-05-22", None, Some("every other weeks"), None)),
        ),
        (
            "extract_every_other_day_count_clause",
            "monday every other day count 5",
            "2026-05-22",
            Some(("2026-05-25", None, Some("every other days count 5"), None)),
        ),
        (
            "extract_every_weekday_tomorrow",
            "tomorrow every weekday",
            "2026-05-22",
            Some(("2026-05-23", None, Some("weekdays"), None)),
        ),
        (
            "extract_every_weekdays_alias_next_friday",
            "next friday every weekdays",
            "2026-05-22",
            Some(("2026-05-29", None, Some("weekdays"), None)),
        ),
        (
            "extract_biweekly_count_clause_iso_date",
            "2026-12-01 biweekly count 3",
            "2026-05-22",
            Some(("2026-12-01", None, Some("biweekly count 3"), None)),
        ),
        (
            "extract_every_other_month_until_clause_iso_date",
            "2026-06-01 every other month until 2027-06-01",
            "2026-05-22",
            Some((
                "2026-06-01",
                None,
                Some("every other months until 2027-06-01"),
                None,
            )),
        ),
        (
            "extract_every_weekday_with_deadline_field",
            "deadline tomorrow every weekday",
            "2026-05-22",
            Some(("2026-05-23", None, Some("weekdays"), Some("deadline"))),
        ),
        (
            "extract_every_other_invalid_unit_rejected",
            "tomorrow every other decade",
            "2026-05-22",
            None,
        ),
    ]
}

fn build_fixture() -> Fixture {
    let cases = raw_cases()
        .into_iter()
        .map(|(name, input, display)| {
            let valid = parse(input).is_some();
            Case {
                name: name.to_string(),
                input: input.to_string(),
                valid,
                canonical_display: display.to_string(),
            }
        })
        .collect();
    let client_extraction_cases = client_extraction_raw_cases()
        .into_iter()
        .map(|(name, input, anchor_date, expected)| ClientExtractionCase {
            name: name.to_string(),
            input: input.to_string(),
            anchor_date: anchor_date.to_string(),
            expected: expected.map(|(date, time, recurrence, field)| ExpectedExtraction {
                date: date.to_string(),
                time: time.map(str::to_string),
                recurrence: recurrence.map(str::to_string),
                field: field.map(str::to_string),
            }),
        })
        .collect();
    Fixture {
        _contract: vec![
            "Shared recurrence-DSL conformance fixture — GENERATED by".to_string(),
            "crates/tesela-core/tests/recurrence_conformance.rs from tesela_core::recurrence::parse.".to_string(),
            "Consumed by the same test (round-trip) plus the web (recurrence-conformance.test.mjs)".to_string(),
            "and iOS (RecurrenceConformanceTests.swift) mirrors. Rust is the source of truth for".to_string(),
            "`valid` AND (as of tesela-pfix.2) `canonical_display`, via tesela_core::recurrence::format".to_string(),
            "— see the module docs in recurrence_conformance.rs.".to_string(),
            "".to_string(),
            "Case shape: { name, input, valid, canonical_display }".to_string(),
        ],
        cases,
        _client_extraction_contract: vec![
            "CLIENT-ONLY section — mixed \"<date phrase> <recurrence phrase>\" EXTRACTION".to_string(),
            "(parseDateAndRecurrenceInput / Swift's DateParser.parse), not standalone".to_string(),
            "parseRecurrenceInput. tesela_core::recurrence has no extraction concept, so unlike".to_string(),
            "`cases` these are PINNED LITERALS (verified against the real web implementation),".to_string(),
            "not derived from a Rust function — see the module docs in recurrence_conformance.rs.".to_string(),
            "".to_string(),
            "Case shape: { name, input, anchor_date, expected: { date, time, recurrence, field } | null }".to_string(),
        ],
        client_extraction_cases,
    }
}

/// Regenerates the on-disk fixture from the case table and asserts the
/// checked-in file is up to date. Run with `UPDATE_FIXTURES=1` to
/// regenerate after editing `raw_cases()`.
#[test]
fn fixture_is_generated_and_up_to_date() {
    let fixture = build_fixture();
    let json = serde_json::to_string_pretty(&fixture).expect("fixture serializes") + "\n";
    let path = fixture_path();

    if std::env::var("UPDATE_FIXTURES").is_ok() || !path.exists() {
        std::fs::write(&path, &json).expect("write recurrence-conformance.json");
    }

    let on_disk = std::fs::read_to_string(&path).expect("read recurrence-conformance.json");
    assert_eq!(
        on_disk, json,
        "recurrence-conformance.json is stale — rerun with UPDATE_FIXTURES=1 to regenerate"
    );
}

/// Case names are unique (they're the cross-language assertion ids).
#[test]
fn case_names_are_unique() {
    let mut seen = std::collections::HashSet::new();
    for (name, _, _) in raw_cases() {
        assert!(seen.insert(name), "duplicate case name: {name}");
    }
}

/// The fixture meets the breadth bar set by query-conformance.json and
/// covers both accept and reject sides of the 2026-06-20 grammar.
#[test]
fn fixture_covers_required_surface() {
    let cases = raw_cases();
    assert!(
        cases.len() >= 30,
        "fixture has {} cases; expected 30+ for full-grammar coverage",
        cases.len()
    );
    let new_grammar = ["biweekly", "fortnightly", "quarterly"];
    for kw in new_grammar {
        assert!(
            parse(kw).is_some(),
            "{kw} must parse — this is the drift this fixture exists to pin"
        );
    }
    assert!(
        parse("every other week").is_some(),
        "'every other <unit>' must parse"
    );
    assert!(
        parse("every weekday").is_some(),
        "'every weekday' must parse"
    );
}

/// Case names are unique within the client-only extraction section too
/// (it has its own namespace from `cases`, but must be internally unique).
#[test]
fn client_extraction_case_names_are_unique() {
    let mut seen = std::collections::HashSet::new();
    for (name, _, _, _) in client_extraction_raw_cases() {
        assert!(seen.insert(name), "duplicate client extraction case name: {name}");
    }
}

/// `tesela_core::recurrence::format` (the FFI-backed formatter iOS now
/// calls, tesela-pfix.2) must reproduce the hand-canonicalized
/// `canonical_display` column for every case — catches drift between the
/// Rust formatter and the web/iOS mirrors immediately.
#[test]
fn format_matches_rust_formatter() {
    let mut failures = Vec::new();
    for (name, input, display) in raw_cases() {
        let got = format(input);
        if got != display {
            failures.push(format!(
                "  {name} — input {input:?}: expected {display:?}, got {got:?}"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} case(s) diverged from tesela_core::recurrence::format:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// The extraction section exercises the trailing form of every new-grammar
/// cadence — this is the gap the tesela-pfix.1 review flagged (extraction
/// cases only existed for the pre-2026-06-20 grammar).
#[test]
fn client_extraction_covers_new_grammar() {
    let cases = client_extraction_raw_cases();
    let inputs: Vec<&str> = cases.iter().map(|(_, input, _, _)| *input).collect();
    for needle in ["biweekly", "fortnightly", "quarterly", "every other", "every weekday"] {
        assert!(
            inputs.iter().any(|i| i.contains(needle)),
            "client_extraction_cases must exercise trailing '{needle}' extraction"
        );
    }
}
